### ISSUE TITLE
File is not extractable

### ISSUE THREAD

**Issue by raydkent86** [KSP-RO/SalyutStations-SoyuzFerries#1]
When I try and extract the .ZIP file in Windows, I can't. An error message is thrown stating an "unexpected error" occured with code 0x80004005. WinRar states there's an "unknown method" in the file. I suspect the files have somehow been corrupted. And where's the download link in the form thread?! All it does is send me to http://mediafire/ or http://download/ ! Please help!

**Comment by raidernick** [comment]
it unzips just fine, to fix the problem follow these steps:
1) Unplug your computer
2) Gently and with great care carry it to your nearest mountain range
3) Throw it off a cliff

**Comment by NathanKell** [comment]
Confirming the issue. What client did you use to zip it, @raidernick  ?

**Comment by NathanKell** [comment]
@rehty77: Meanwhile, get the repo by going to the main repo page and clicking 'download zip.' That will at least get you the files.

**Comment by raidernick** [comment]
7zip and it works just fine, but just because this is becoming a big issue I rezipped it with winrar, go wild.
