### ISSUE TITLE
In Realism Overhaul, the Vostok ends up exploding on reentry back to Earth for no apparent reason

### ISSUE THREAD

**Issue by raydkent86** [KSP-RO/SalyutStations-SoyuzFerries#2]
Whenever I try and reenter the Earth's atmosphere, even though it says ablation is taking place, the entire capsule explodes as if there's no ablative shielding at all. I am using Realism Overhaul for 1.0.2 with Deadly Reentry, so either this is a DRE bug that I need to tell the devs of the plugin about, or you've configured it wrong for RO so it treats it as if it's not aerodynamically shielded. Please help, as this is ruining my game.

**Comment by NathanKell** [comment]
Upgrade to 1.0.4 and uninstall DeadlyReentry. Make sure you get RealHeat too, RO requires it.
