### ISSUE TITLE
Vostok/Voshod REALLY Deadly Re-entry

### ISSUE THREAD

**Issue by nonalaker** [KSP-RO/SalyutStations-SoyuzFerries#3]
Hello!

I've got a serious problem. After many trials of descension (different angles, Pe/Ap etc), I stuck. The advice given here:[https://github.com/KSP-RO/SalyutStations-SoyuzFerries/issues/2](url)
did not work. Every time I try to come back, my Jeb Gagarin dies.

My version of KSP: 1.0.5. Here is my plug list:
![plugs](https://cloud.githubusercontent.com/assets/17145835/12923848/9f1239e8-cf57-11e5-938d-46229190cb4d.jpg)

I just want to add, that when I uninstalled DRC, same things happened. Vostok just overheats at height of ~80-75 kms and explodes. Other spacecrafts (ex. Soyuz, Progress etc) behave normally. 

Does any solution exsist?

**Comment by raidernick** [comment]
This is a known issue and looks like it was forgotten to be fixed in the latest RO. There is an open pull request there for a fix, you can try out those files and see if they work for you.

**Comment by nonalaker** [comment]
Ok, so after few attempts:

Vostok capsule reenters the atmosphere. Ablator works normally, the amount is decreasing. Previously it was "indestroyable". Now Vostok can touch the ground. Thank you very much!

There are just two little "ahems": what about parachutes/parachute shell? Every time (about 5-6 attempts) it exploded due to overheating. Is it normal or the shell/chute should be also fixed? Maybe some ablator should be added or taken from the main part? Ex: chute 25/200 capsule.

The second one: the service module (no ablator, big drogue etc) survived the reentry. What is more: wasn't even damaged. Shouldn't be disintegrated in upper atmo?

**Comment by raidernick** [comment]
play around with the max temp settings for those parts in the ro configs then. I am very busy and don't have time to test it ingame. Let me know what values work.

**Comment by raidernick** [comment]
Issue has been fixed, it turns out it was a ro issue not a config issue.
