### ISSUE TITLE
Solar Panel output wrong?

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/SalyutStations-SoyuzFerries#8]
Since Salyut Stations patches itself for RO compatibility (also probably an issue, but a lesser one), I have opened this issue here. Although sources are hard to come by for Soviet Spacecraft, it seems like the power output of many of the solar panels in this pack are incorrect.

The values set right now, and what sources I can find, list suspiciously low power output for the solar panel surface area, compared to other contemporary panels. Even assuming Soviet panels had half the efficiency of US panels, the power output is much lower than it should be. With kerbalism installed, the stations struggle to even match the life support loads kerbalism calculates for them.

I believe the values that have been set (and that are found in english literature) are the _average_ power output of the solar panels, which is roughly half the peak power output, since the stations will spend about half their time in darkness. The Solar panels in Soviet Spacecraft may also have incorrect power generation, but Soyuz has a shorter on-orbit lifetime, so the power shortage is less noticeable.

**Comment by raidernick** [comment]
Feel free to make any changes to the solar output here or in RO. Just make sure that you don't change any resource values as it will break craft files. Just changing the panel output won't break anything.
